branches:
  only:
  - master
  - /^it\/.*$/
language: minimal
services:
- docker
script: cd infrastructure-tests && chmod +x runTests.sh && ./runTests.sh
notifications:
  slack:
    on_success: never
    on_failure: always
    secure: BhZiXHoL0/zLHLOqpwFdBNJy5iMfdxtPz1CZY3mzxJUxwG0sr9foR8GP0VtX48osnKN6uj1SeE2/MZpyqde3xBnThcADqwSniWy+Pwzl4KiNcEE9DycHWn7dFmreYBUiwTukuv4atIBBu79TnYyXQ0pFWTx46QXYnHNE7W+tFmri+R18Akt8XRAW0oIi3N1IqQri5V8xOGRQ34L6Hi5rMLwVfCp52OCovdgVtcx7KdgQ1Xo+UIpWbHaW1uJSnrbr/J9nTXeizYG2hJ/4TMB876kua1ehvkDGi1jPdLuxPm4K5ViHfCVH00xA7v1RAa4qK7JgTxNlIjh22wqKSVFWAx5APrgbGyyLm0kGxAW7lB2d+2Y7IG1qEKZ8TZPvk7P21Sn/lY6iMg6zkde5eZm4pm6DIYIGtSVFLxDFx1c8S9FRnjQUfIVvLzv4JhiNizpTvUe9K1KBNg93O2gyurCjG/jaU2uoAEScoCuh0XLVKJ+OJx2VGQ0r2NDnNqE5MBAJPP/udON+BLjB+umxccU5pnU4B8c2EvbCb3bSLUahU8+ZXI64EDl3lHGbRZVYdxOG22hZ2Z9LdgfIfNfpiM+oRrFK78vD9OHvsZGdeflpR3/yTY31QFveeOodud0bfkMaCXNEFtpRgAyveMVwN9bbZNCR1hat/IE2PHDEF3uNrYA=
